name: deploy

env:
  URL_CHECKER_TIMEOUT: 1
  PATH_PREFIX: /cd13461/

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - CONTRIBUTING.md
      - LICENSE

jobs:
  test:
    timeout-minutes: 2
    strategy:
      fail-fast: true
      max-parallel: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - run: npm run lint:all
      - run: node script/url-checker.js -t $URL_CHECKER_TIMEOUT
  build:
    needs: test
    timeout-minutes: 2
    strategy:
      fail-fast: true
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - uses: actions/configure-pages@v4
      - run: npm install
      - run: npm run prod
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "./_site"
  # deploy:
  #   timeout-minutes: 2
  #   strategy:
  #     fail-fast: true
  #     max-parallel: 1